version: '3.4'

services:
  php:
    build: ./docker/php 
    restart: unless-stopped
    volumes:
      - .${APP_ROOT}:${APP_ROOT}
    working_dir: ${APP_ROOT}
    user: '1000:1000'
    ports:
      - 8000:8000
    command: php -S 0.0.0.0:8000 -t ${APP_ROOT}
